### PR TITLE
Added jest & sample spec

### LINKED ISSUE #4: Add jest
- Add jest for unit testing the CLI
- Add one simple spec file

### PR DESCRIPTION
**Pull request by kuldeepkeshwar**
close #4

### CODE REVIEW

**Comment by antonybudianto** [comment]
Please also update Travis file to run this test as well, thank you

**Comment by antonybudianto** [comment]
The test is failed due to it runs npm test on the wrong directory

**Comment by kuldeepkeshwar** [comment]
@antonybudianto add test command to Travis

**Comment by antonybudianto** [comment]
please fix the test first, then I can merge

**Comment by antonybudianto** [comment]
Thank you @kuldeepkeshwar 🎉

**Pull request merged**
